# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000
add_newline = false

right_format = "$kubernetes"

[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[aws]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context]($style) [\($namespace\)](blue)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
